### ISSUE TITLE
index.ts is missing

### ISSUE THREAD

**Issue by shakesBeardZ** [mdbootstrap/Angular-Bootstrap-with-Material-Design#52]
```
ERROR in ./node_modules/angular-bootstrap-md/index.ts
Module build failed: Error: <Project_Path>\mdBoots4\node_modules\angular-bootstrap-md\index.ts is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.
The missing file seems to be part of a third party library. TS files in published libraries are often a sign of a badly packaged library. Please open an issue in the library repository to alert its author and ask them to package the library using the Angular Package Format (https://goo.gl/jB3GVv).
    at AngularCompilerPlugin.getCompiledFile (<Project_Path>\mdBoots4\node_modules\@ngtools\webpack\src\angular_compiler_plugin.js:662:23)
    at plugin.done.then (<Project_Path>\mdBoots4\node_modules\@ngtools\webpack\src\loader.js:467:39)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
 @ ./src/app/app.module.ts 11:29-60
 @ ./src/main.ts
 @ multi webpack-dev-server/client?http://0.0.0.0:0 ./src/main.ts
```
Angular 5.2.0
Angular CLI: 1.6.7

**Comment by shakesBeardZ** [comment]
I struggled with this error for like 30 minutes but when I exited and run `ng serve` again it worked normally
