### ISSUE TITLE
Getting badly packaged library error while writing test cases in MDB Angular.

### ISSUE THREAD

**Issue by Gurpreet-Chhabra** [mdbootstrap/Angular-Bootstrap-with-Material-Design#80]
ERROR in ./node_modules/ng-mdb-pro/index.ts
Module build failed: Error: /Users/app/node_modules/ng-mdb-pro/index.ts is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.
The missing file seems to be part of a third party library. TS files in published libraries are often a sign of a badly packaged library. Please open an issue in the library repository to alert its author and ask them to package the library using the Angular Package Format (https://goo.gl/jB3GVv).
    at AngularCompilerPlugin.getCompiledFile (/Users/app/node_modules/@ngtools/webpack/src/angular_compiler_plugin.js:674:23)
    at plugin.done.then (/Users/app/node_modules/@ngtools/webpack/src/loader.js:467:39)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
 @ ./src/app/_shared/sha.module.ts 12:19-40 13:19-40
 @ ./src/app/emp/employees.module.ts
 @ ./src/app/app.module.ts
 @ ./src/app/pay/admin/overview.component.spec.ts
 @ ./src \.spec\.ts$
 @ ./src/test.ts

**Comment by Bloodcast69** [comment]
Dear @Gurpreet-Chhabra which version of MDB Angular you're using? MDB Angular Pro or MDB Angular Free? And in which version exactly?

**Comment by Gurpreet-Chhabra** [comment]
I am using MDB Angular Pro  for Angular 5.

**Comment by Bloodcast69** [comment]
Could you add 
`"include": ["node_modules/ng-mdb-pro/**/*.ts",  "src/**/*.ts"],`
in your tsconfig.json file? Also you have to import our MDB Angular Pro module in every component which you're testing.
Please let me know if it works now.

**Comment by Gurpreet-Chhabra** [comment]
Tried including "include": ["node_modules/ng-mdb-pro/**/*.ts", "src/**/*.ts"] in my tsconfig and imported the MDB Angular Pro module in my file be tested.But I am still getting the same error.
