### ISSUE TITLE
mdbInputDirective error: callback must be a function

### ISSUE THREAD

**Issue by xcash** [mdbootstrap/Angular-Bootstrap-with-Material-Design#83]
### Expected behavior
No errors in console.

### Actual behavior
When using mdbInputDirective as from docs every keypress throws the following error in console:

```
ERROR NodeError: Callback must be a function
    at setTimeout (timers.js:379:11)
    at chrome-extension://kcdkljijkdhmhjkjdkliemkkgfgfhgpc/polyfills.js:4442:33
    at proto.(anonymous function) (chrome-extension://kcdkljijkdhmhjkjdkliemkkgfgfhgpc/polyfills.js:3716:24)
    at MdbInputDirective.push../node_modules/angular-bootstrap-md/esm5/angular-bootstrap-md.es5.js.MdbInputDirective.delayedResize (chrome-extension://kcdkljijkdhmhjkjdkliemkkgfgfhgpc/vendor.js:104497:9)
    at MdbInputDirective.push../node_modules/angular-bootstrap-md/esm5/angular-bootstrap-md.es5.js.MdbInputDirective.onkeydown (chrome-extension://kcdkljijkdhmhjkjdkliemkkgfgfhgpc/vendor.js:104351:14)
    at Object.eval [as handleEvent] (ng:///AppModule/AppComponent.ngfactory.js:99:50)
    at handleEvent (chrome-extension://kcdkljijkdhmhjkjdkliemkkgfgfhgpc/vendor.js:39338:41)
    at callWithDebugContext (chrome-extension://kcdkljijkdhmhjkjdkliemkkgfgfhgpc/vendor.js:40431:25)
    at Object.debugHandleEvent [as handleEvent] (chrome-extension://kcdkljijkdhmhjkjdkliemkkgfgfhgpc/vendor.js:40134:12)
    at dispatchEvent (chrome-extension://kcdkljijkdhmhjkjdkliemkkgfgfhgpc/vendor.js:36797:25)
```

### Your working environment and MDB version information
Angular 6.0.9
Angular MDBootstrap 6.0.4 and 6.0.6

### Resources (screenshots, code snippets etc.)

Simple as a simple form field

```
<div class="md-form">
  <i class="fa fa-envelope prefix grey-text"></i>
  <input mdbInputDirective type="text" id="loginForm-email" class="form-control">
  <label for="loginForm-email">Email</label>
</div>
```

**Comment by Bloodcast69** [comment]
@xcash , Could you please check if this problem exists with the latest version of MDB Angular? - 6.2.0.

**Comment by xcash** [comment]
@Bloodcast69 It's still present.
Every keypress event I see that error in console. 
If i omit `mdInputDirective` no more console.error. Just to exclude issues in other parts of the code.

**Comment by Bloodcast69** [comment]
@xcash Unfortunately I'm unable to reproduce your case on my app. 

Could you please provide me with reproduction repository on which I'll be able to test your case?

**Comment by xcash** [comment]
@bloodcast69 sure. In a few days i'll prepare a repo.


Il mar 17 lug 2018, 07:44 Bloodcast69 <notifications@github.com> ha scritto:
