### ISSUE TITLE
npm start errrorsa

### ISSUE THREAD

**Issue by bbehling-trimble** [mdbootstrap/Angular-Bootstrap-with-Material-Design#93]
### Expected behavior
npm start to serve mdbootstrap demo app
### Actual behavior
errors:
Could not determine a single project for the 'serve' target.
Error: Could not determine a single project for the 'serve' target.
    at ServeCommand.getProjectNamesByTarget (/home/dev1/code/mdb-angular-free-6.2.5/node_modules/@angular/cli/models/architect-command.js:175:19)
    at MergeMapSubscriber._loadWorkspaceAndArchitect.pipe.operators_1.concatMap [as project] (/home/dev1/code/mdb-angular-free-6.2.5/node_modules/@angular/cli/models/architect-command.js:50:43)
    at MergeMapSubscriber._tryNext (/home/dev1/code/mdb-angular-free-6.2.5/node_modules/rxjs/internal/operators/mergeMap.js:65:27)
    at MergeMapSubscriber._next (/home/dev1/code/mdb-angular-free-6.2.5/node_modules/rxjs/internal/operators/mergeMap.js:55:18)
    at MergeMapSubscriber.Subscriber.next (/home/dev1/code/mdb-angular-free-6.2.5/node_modules/rxjs/internal/Subscriber.js:64:18)
    at TapSubscriber._next (/home/dev1/code/mdb-angular-free-6.2.5/node_modules/rxjs/internal/operators/tap.js:62:26)
    at TapSubscriber.Subscriber.next (/home/dev1/code/mdb-angular-free-6.2.5/node_modules/rxjs/internal/Subscriber.js:64:18)
    at MergeMapSubscriber.notifyNext (/home/dev1/code/mdb-angular-free-6.2.5/node_modules/rxjs/internal/operators/mergeMap.js:84:26)
    at InnerSubscriber._next (/home/dev1/code/mdb-angular-free-6.2.5/node_modules/rxjs/internal/InnerSubscriber.js:25:21)
    at InnerSubscriber.Subscriber.next (/home/dev1/code/mdb-angular-free-6.2.5/node_modules/rxjs/internal/Subscriber.js:64:18)

Logfile:
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'start' ]
2 info using npm@6.4.1
3 info using node@v10.11.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle mdb-angular-free@6.2.5~prestart: mdb-angular-free@6.2.5
6 info lifecycle mdb-angular-free@6.2.5~start: mdb-angular-free@6.2.5
7 verbose lifecycle mdb-angular-free@6.2.5~start: unsafe-perm in lifecycle true
8 verbose lifecycle mdb-angular-free@6.2.5~start: PATH: /usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/dev1/code/mdb-angular-free-6.2.5/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/usr/lib/jvm/java-8-oracle/bin:/usr/lib/jvm/java-8-oracle/db/bin:/usr/lib/jvm/java-8-oracle/jre/bin:/home/dev1/npm/bin
9 verbose lifecycle mdb-angular-free@6.2.5~start: CWD: /home/dev1/code/mdb-angular-free-6.2.5
10 silly lifecycle mdb-angular-free@6.2.5~start: Args: [ '-c', 'ng serve' ]
11 silly lifecycle mdb-angular-free@6.2.5~start: Returned: code: 1  signal: null
12 info lifecycle mdb-angular-free@6.2.5~start: Failed to exec start script
13 verbose stack Error: mdb-angular-free@6.2.5 start: `ng serve`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:301:16)
13 verbose stack     at EventEmitter.emit (events.js:182:13)
13 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:182:13)
13 verbose stack     at maybeClose (internal/child_process.js:962:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)
14 verbose pkgid mdb-angular-free@6.2.5
15 verbose cwd /home/dev1/code/mdb-angular-free-6.2.5
16 verbose Linux 4.15.0-36-generic
17 verbose argv "/usr/bin/node" "/usr/bin/npm" "start"
18 verbose node v10.11.0
19 verbose npm  v6.4.1
20 error code ELIFECYCLE
21 error errno 1
22 error mdb-angular-free@6.2.5 start: `ng serve`
22 error Exit status 1
23 error Failed at the mdb-angular-free@6.2.5 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

### Your working environment and MDB version information
Angular CLI 6.0.8
mdb v6.2.5
For every **question of technical nature**, in order to get the most detailed answer as soon as possible, ask on our dedicated [Support Forum](https://mdbootstrap.com/support/)

**Comment by bbehling-trimble** [comment]
I watched the quick start video, and it said to run npm start. 

After reading the readme include with the download, the correct command should be ng serve with the project name.

ng serve mdb-demo
